### PR TITLE
Bug 1986462: Separate the names of machine os downloader when two copies are started 

### PR DESCRIPTION
**Pull request by kirankt**
When specifying both PreProvisioningOSDownloadURLs and ProvisioningOSDownloadURL in the provisioning config CR, CBO will fail to reconcile becasuse two copies of machine-os-downloader init containers with the same name are started. The names of these initcontainers should be different when both of them are spawned together.

### CODE REVIEW

**Review by asalkeld — COMMENTED** [review]
can you create a new unit test section like this https://github.com/openshift/cluster-baremetal-operator/blob/master/provisioning/baremetal_pod_test.go#L330-L346
but with the PreProvisioningOSDownloadURLs defined

**Comment by kirankt** [comment]
> can you create a new unit test section like this https://github.com/openshift/cluster-baremetal-operator/blob/master/provisioning/baremetal_pod_test.go#L330-L346
> but with the PreProvisioningOSDownloadURLs defined

This PR only deals with the initContainers. We don't really mess with the existing containers in the pod. But I will add a section in the initContainers. Realistically there should be another PR that should validate the preProvisioningOSDownloadURLs and perform unit testing on them.

**Review by sadasu — COMMENTED** [review]
/lgtm

**Pull request merged**
