### PR TITLE
OCPBUGS-36285: Mount htpasswds as volumeMounts in metal3-httpd container

### PR DESCRIPTION
**Pull request by MahnoorAsghar**
This is a backport of PR #408

### CODE REVIEW

**Comment by MahnoorAsghar** [comment]
/test e2e-metal-ipi-ovn-virtualmedia
/test e2e-metal-ipi-ovn-dualstack
The failures seem unrelated to the PR

**Comment by dtantsur** [comment]
/approve
/label backport-risk-assessed
/hold

https://github.com/openshift/ironic-image/pull/517 must merge first, otherwise we're left without authentication. Please retry a few jobs and check the results before unholding.

**Comment by MahnoorAsghar** [comment]
/test e2e-metal-ipi-bm
/test e2e-metal-ipi-ovn-virtualmedia

The CI jobs ran an old ironic-image version (commit hash 9d49fd6). I need the ironic-image to contain [this fix](https://github.com/openshift/ironic-image/pull/517); so that I can verify that authentication is working with it and this change combined.
(ironic-image version information was found in this file: ./artifacts/e2e-metal-ipi-bm/gather-extra/artifacts/releaseinfo.json)

**Comment by MahnoorAsghar** [comment]
/test e2e-metal-ipi-bm
Retesting as the failure looks unrelated.

`e2e-metal-ipi-ovn-virtualmedia` ran with ironic-image with commit hash 39aee9b (which means the relevant change is present in ironic-image). The httpd container has the ironic and inspector htpasswds available as per its logs in the must-gather.tar file [here](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-baremetal-operator/434/pull-ci-openshift-cluster-baremetal-operator-release-4.16-e2e-metal-ipi-ovn-virtualmedia/1811784491966926848/artifacts/e2e-metal-ipi-ovn-virtualmedia/gather-must-gather/artifacts/). Its volume mounts and volume configuration is also as expected.

**Comment by MahnoorAsghar** [comment]
/unhold
Test e2e-metal-ipi-bm also has authentication enabled correctly.

**Pull request merged**
