### PR TITLE
Revert "proxy: pass ipv6 address to container"

### PR DESCRIPTION
**Pull request by dtantsur**
First and foremost, it made the proxy refer to itself, which only
happens to work when the API VIP is on the same master as the metal3
pod. Proxy must use the real pod IP.

The UPSTREAM_*_V6 variables do not exist in ironic-image, setting
them does nothing. On top of that, passing several upstream IPs does not
make much sense: we expect that Ironic is available on any of the valid
IPs, and we can make the proxy contact any of them.

This reverts commit ba7403e57e344e615d375af5cb7bfec5d56f03e9.

### CODE REVIEW

**Comment by zaneb** [comment]
Do we expect everything to be correct after this revert, or is there something else we now need to do instead?

**Comment by dtantsur** [comment]
> Do we expect everything to be correct after this revert, or is there something else we now need to do instead?

I hope that the external IP PR still works. This change only concerns how the proxy itself connects to the pod, while the Honza's PR was about using the proxy. Worth confirming though since virtual media is not tested with dualstack in the CI.

**Pull request merged**
