### PR TITLE
OCPBUGS-33493: Enable leader election for baremetal-operator

### PR DESCRIPTION
**Pull request by honza**
* ~Depends on https://github.com/metal3-io/baremetal-operator/pull/1725~

### CODE REVIEW

**Comment by zaneb** [comment]
We need to make sure that the timeouts are all configured according to OpenShift standards (see e.g. https://github.com/openshift/cluster-baremetal-operator/pull/403).

**Comment by honza** [comment]
> Is that in progress also?

I just opened an [upstream PR](https://github.com/metal3-io/baremetal-operator/pull/1725) to add more `ctlr.Options` knobs.  The present PR has been updated to make use of the new knobs in anticipation.

**Comment by zaneb** [comment]
I wouldn't have expected tests to pass before openshift/baremetal-operator#354 merged, but hopefully they should now.
/lgtm
/retest

**Comment by zaneb** [comment]
/retitle OCPBUGS-33493: Enable leader election for baremetal-operator

**Comment by honza** [comment]
> I wouldn't have expected tests to pass before https://github.com/openshift/baremetal-operator/pull/354 merged, but hopefully they should now.

I think I hit the retest 10 mins after it merged.  Do we usually need to wait longer?

**Comment by zaneb** [comment]
> > I wouldn't have expected tests to pass before [openshift/baremetal-operator#354](https://github.com/openshift/baremetal-operator/pull/354) merged, but hopefully they should now.
> 
> I think I hit the retest 10 mins after it merged. Do we usually need to wait longer?

Sorry, I was looking at the wrong timestamp (the one from the ART bot saying it was in a build downstream).

It does take a while for the post-merge jobs to run and promote the new image into the CI repo. As far as I know there's nowhere you can easily tell when exactly that happens. I have definitely seen it fail to pick stuff up after 10mins.

**Comment by zaneb** [comment]
must-gather confirms that the previous test failures were due to the image not propagating yet:

```
2024-05-15T14:21:09.594617617Z flag provided but not defined: -lease-duration-seconds
2024-05-15T14:21:09.594617617Z Usage of /baremetal-operator:
2024-05-15T14:21:09.594617617Z   -build-preprov-image
2024-05-15T14:21:09.594617617Z     	enable integration with the PreprovisioningImage API
2024-05-15T14:21:09.594617617Z   -controller-concurrency int
2024-05-15T14:21:09.594617617Z     	Number of CRs of each type to process simultaneously
2024-05-15T14:21:09.594617617Z   -demo-mode
2024-05-15T14:21:09.594617617Z     	use the demo provisioner to set host states
2024-05-15T14:21:09.594617617Z   -dev
2024-05-15T14:21:09.594617617Z     	enable developer logging
2024-05-15T14:21:09.594617617Z   -enable-leader-election
2024-05-15T14:21:09.594617617Z     	Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
2024-05-15T14:21:09.594617617Z   -health-addr string
2024-05-15T14:21:09.594617617Z     	The address the health endpoint binds to. (default ":9440")
2024-05-15T14:21:09.594741037Z   -kube-api-burst int
2024-05-15T14:21:09.594741037Z     	Maximum number of queries that should be allowed in one burst from the controller client to the Kubernetes API server. Default 30 (default 30)
2024-05-15T14:21:09.594741037Z   -kube-api-qps float
2024-05-15T14:21:09.594741037Z     	Maximum queries per second from the controller client to the Kubernetes API server. Default 20 (default 20)
2024-05-15T14:21:09.594741037Z   -kubeconfig string
2024-05-15T14:21:09.594741037Z     	Paths to a kubeconfig. Only required if out-of-cluster.
2024-05-15T14:21:09.594741037Z   -metrics-addr string
2024-05-15T14:21:09.594741037Z     	The address the metric endpoint binds to. (default "127.0.0.1:8085")
2024-05-15T14:21:09.594741037Z   -namespace string
2024-05-15T14:21:09.594741037Z     	Namespace that the controller watches to reconcile host resources. (default "openshift-machine-api")
2024-05-15T14:21:09.594741037Z   -test-mode
2024-05-15T14:21:09.594741037Z     	disable ironic communication
2024-05-15T14:21:09.594741037Z   -tls-cipher-suites string
2024-05-15T14:21:09.594741037Z     	Comma-separated list of cipher suites for the webhook server. If omitted, the default Go cipher suites will be used. 
2024-05-15T14:21:09.594741037Z     	Preferred values: TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384. 
2024-05-15T14:21:09.594741037Z     	Insecure values: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_RC4_128_SHA.
2024-05-15T14:21:09.594741037Z   -tls-max-version string
2024-05-15T14:21:09.594741037Z     	The maximum TLS version in use by the webhook server.
2024-05-15T14:21:09.594741037Z     	Possible values are TLS12, TLS13. (default "TLS13")
2024-05-15T14:21:09.594741037Z   -tls-min-version string
2024-05-15T14:21:09.594741037Z     	The minimum TLS version in use by the webhook server.
2024-05-15T14:21:09.594741037Z     	Possible values are TLS12, TLS13. (default "TLS12")
2024-05-15T14:21:09.594741037Z   -webhook-port int
2024-05-15T14:21:09.594741037Z     	Webhook Server port (set to 0 to disable) (default 9443)
```

**Pull request merged**
