### PR TITLE
Bug 2041510: Enable webhook for bmceventsubscriptions

### PR DESCRIPTION
**Pull request by honza**
@ardaguclu Is this enough to enable it? Do I need to do anything else?

### CODE REVIEW

**Comment by omichaeli** [comment]
@honza Should the bmceventsubscription be in plural?

**Comment by honza** [comment]
> @honza Should the bmceventsubscription be in plural?

Yes. :man_facepalming:

**Comment by ardaguclu** [comment]
@honza this looks good to me and should be enough.

I highly suggest to add a test to check that endpoint is healthy like in here https://github.com/openshift/origin/blob/b5c202c718553f4124030ce2b21a1d7059ee37cf/test/extended/baremetal/hosts.go#L244.

/lgtm
/e2e-agnostic

**Review by bfournie — APPROVED** [review]

**Pull request merged**
