### PR TITLE
Add baremetal capability annotations

### PR DESCRIPTION
**Pull request by honza**
The capability [has already been registered](https://github.com/openshift/api/pull/1125) with the API.

### CODE REVIEW

**Comment by sadasu** [comment]
Does the BMH CRD also need this annonation? That would mean that we have to add this capability annotation to https://github.com/openshift/baremetal-operator/blob/master/config/crd/ocp/ocp_kustomization.yaml too.

**Comment by honza** [comment]
Or should it be an annotation [on the container in CBO](https://github.com/openshift/cluster-baremetal-operator/blob/master/provisioning/baremetal_pod.go#L437)?

**Comment by wking** [comment]
In case it helps, recent nightly:

```console
$ oc adm release extract --to manifests registry.ci.openshift.org/ocp/release:4.11.0-0.nightly-2022-03-09-235248
Extracted release payload from digest sha256:05d922e0df6b70ec6170602c4ae374b04a94dd0fe552ea668a20782c2afe5158 created at 2022-03-09T23:56:42Z
$ ls manifests/*metal*
manifests/0000_30_baremetal-operator_01_baremetalhost.crd.yaml
manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
manifests/0000_31_cluster-baremetal-operator_01_trusted-ca-configmap.yaml
manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
manifests/0000_31_cluster-baremetal-operator_03_service.yaml
manifests/0000_31_cluster-baremetal-operator_03_webhookservice.yaml
manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
manifests/0000_31_cluster-baremetal-operator_05_kube-rbac-proxy-config.yaml
manifests/0000_31_cluster-baremetal-operator_05_prometheus_rbac.yaml
manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
```

Unclear to me why the BareMetalHost CRD is at level 30.  Looks like that's coming from [here][1].  Perhaps it should be adjusted to use a `manifests/0000_31_cluster-baremetal-operator_...` prefix?  But all of those manifests look like they could use `capability.openshift.io/name= baremetal` to me.

[1]: https://github.com/openshift/baremetal-operator/blob/1206303e237a228b033f99c35fb71a231f3355b3/Dockerfile.ocp#L11

**Comment by sadasu** [comment]
> Or should it be an annotation [on the container in CBO](https://github.com/openshift/cluster-baremetal-operator/blob/master/provisioning/baremetal_pod.go#L437)?

This capability annotation is only required on resources managed by CVO, afaik. The BMO container, which is part of the metal3 deployment is a resource managed by CBO and hence doesn't need this annotation.

We still need to add the capability annotation to the the BMH CRD because that is a manifest that is generated here : https://github.com/openshift/baremetal-operator/blob/master/Dockerfile.ocp and installed by CVO. So, adding the capability annotation to https://github.com/openshift/baremetal-operator/blob/master/config/crd/ocp/ocp_kustomization.yaml would make sure the generated manifest would have it.

**Comment by sadasu** [comment]
> In case it helps, recent nightly:
> 
> ```
> $ oc adm release extract --to manifests registry.ci.openshift.org/ocp/release:4.11.0-0.nightly-2022-03-09-235248
> Extracted release payload from digest sha256:05d922e0df6b70ec6170602c4ae374b04a94dd0fe552ea668a20782c2afe5158 created at 2022-03-09T23:56:42Z
> $ ls manifests/*metal*
> manifests/0000_30_baremetal-operator_01_baremetalhost.crd.yaml
> manifests/0000_31_cluster-baremetal-operator_01_images.configmap.yaml
> manifests/0000_31_cluster-baremetal-operator_01_trusted-ca-configmap.yaml
> manifests/0000_31_cluster-baremetal-operator_02_metal3provisioning.crd.yaml
> manifests/0000_31_cluster-baremetal-operator_03_service.yaml
> manifests/0000_31_cluster-baremetal-operator_03_webhookservice.yaml
> manifests/0000_31_cluster-baremetal-operator_04_serviceaccount.yaml
> manifests/0000_31_cluster-baremetal-operator_05_kube-rbac-proxy-config.yaml
> manifests/0000_31_cluster-baremetal-operator_05_prometheus_rbac.yaml
> manifests/0000_31_cluster-baremetal-operator_05_rbac.yaml
> manifests/0000_31_cluster-baremetal-operator_06_deployment.yaml
> manifests/0000_31_cluster-baremetal-operator_07_clusteroperator.cr.yaml
> manifests/0000_90_cluster-baremetal-operator_03_servicemonitor.yaml
> ```
> 
> Unclear to me why the BareMetalHost CRD is at level 30. Looks like that's coming from [here](https://github.com/openshift/baremetal-operator/blob/1206303e237a228b033f99c35fb71a231f3355b3/Dockerfile.ocp#L11). Perhaps it should be adjusted to use a `manifests/0000_31_cluster-baremetal-operator_...` prefix? But all of those manifests look like they could use `capability.openshift.io/name: baremetal` to me.

@wking Your list is correct and that is what we are working towards. We wanted to make sure manifests/0000_30_baremetal-operator_01_baremetalhost.crd.yaml is installed before the rest of the CBO manifests hence the level 30. The manifest is generated by openshift/baremetal_operator (https://github.com/openshift/baremetal-operator/blob/master/Dockerfile.ocp#L11) as you correctly pointed out hence the name of the manifest has "baremetal_operator" and not "cluster_baremetal_operator". The rest of the manifests in that list are provided by the cluster_baremetal_operator.

**Comment by honza** [comment]
> @honza This capability annotation is only required on resources managed by CVO, afaik. The BMO container, which is part of the metal3 deployment is a resource managed by CBO and hence doesn't need this annotation.

Oh, yes, I remember now! 

https://github.com/openshift/baremetal-operator/pull/212

**Comment by sadasu** [comment]
> > We still need to add the capability annotation to the the BMH CRD because that is a manifest that is generated here : https://github.com/openshift/baremetal-operator/blob/master/Dockerfile.ocp and installed by CVO. So, adding the capability annotation to https://github.com/openshift/baremetal-operator/blob/master/config/crd/ocp/ocp_kustomization.yaml would make sure the generated manifest would have it.
> 
> Oh, yes, I remember now!
> 
> [openshift/baremetal-operator#212](https://github.com/openshift/baremetal-operator/pull/212)

In openshift/baremetal-operator, the annotation is added with "baremetal" (https://github.com/openshift/baremetal-operator/pull/212/files) and here in CBO it is without " ". Which one should it be?

**Comment by honza** [comment]
Fixed by removing the quotes. But I can't imagine that it would matter?

**Comment by wking** [comment]
> We wanted to make sure `manifests/0000_30_baremetal-operator_01_baremetalhost.crd.yaml` is installed before the rest of the CBO manifests hence the level 30.

The CVO collects manifests into [task nodes][1], which share the same level/name prefix.  So you currently have two task-nodes, one of `30_baremetal-operator` and one for `31_cluster-baremetal-operator`.  During updates, level 30 task nodes will be processed before level 31 task nodes.  But during install and reconciliation [we flatten the task-node graph, so levels don't matter][1].  However, regardless of the CVO mode, we always order manifests within a task node.  So moving the CRD to `0000_31_cluster-baremetal-operator_00_baremetalhost.crd.yaml` or something similar that begins with `0000_31_cluster-baremetal-operator_` and sorts before the other `0000_31_cluster-baremetal-operator_...` entries, would ensure the CRD comes first in all CVO modes, while your current level 30 only gets it coming first in update mode. 

[1]: https://github.com/openshift/enhancements/blob/7e6d4c107fc64ad8cc3e5e6cb5f89cf2d852849f/dev-guide/cluster-version-operator/user/reconciliation.md#manifest-graph

**Comment by honza** [comment]
It seems to me that the errors in e2e-metal-ipi-ovn-ipv6 aren't related to the changes in this PR. Given that the other jobs passed on the first try, I think we're safe to override here.

/override ci/prow/e2e-metal-ipi-ovn-ipv6

**Comment by sadasu** [comment]
> Fixed by removing the quotes. But I can't imagine that it would matter?
Looking at the enhancement proposal https://github.com/openshift/enhancements/blob/master/enhancements/installer/component-selection.md, I see :
annotations:
  capability.openshift.io/name: "console"

**Comment by honza** [comment]
> The CVO collects manifests into [task nodes](https://github.com/openshift/enhancements/blob/7e6d4c107fc64ad8cc3e5e6cb5f89cf2d852849f/dev-guide/cluster-version-operator/user/reconciliation.md#manifest-graph), which share the same level/name prefix. So you currently have two task-nodes, one of `30_baremetal-operator` and one for `31_cluster-baremetal-operator`. During updates, level 30 task nodes will be processed before level 31 task nodes. But during install and reconciliation [we flatten the task-node graph, so levels don't matter](https://github.com/openshift/enhancements/blob/7e6d4c107fc64ad8cc3e5e6cb5f89cf2d852849f/dev-guide/cluster-version-operator/user/reconciliation.md#manifest-graph). However, regardless of the CVO mode, we always order manifests within a task node. So moving the CRD to `0000_31_cluster-baremetal-operator_00_baremetalhost.crd.yaml` or something similar that begins with `0000_31_cluster-baremetal-operator_` and sorts before the other `0000_31_cluster-baremetal-operator_...` entries, would ensure the CRD comes first in all CVO modes, while your current level 30 only gets it coming first in update mode.

Thanks for the explanation. I opened a follow-up PR: https://github.com/openshift/baremetal-operator/pull/216

**Pull request merged**
