### PR TITLE
Allow access to InfraEnv resources from assisted service

### PR DESCRIPTION
**Pull request by dtantsur**
We will need to read and modify them in image-customization-controller:
- https://github.com/openshift/image-customization-controller/pull/42

### CODE REVIEW

**Comment by sadasu** [comment]
Do you  need to enable rbacs for watch?

**Comment by dtantsur** [comment]
I don't think so. ICC is not going to use a client cache for these resources, nor watch for their changes.

Maybe later... definitely not in the first iteration.

**Review by flaper87 — COMMENTED** [review]
/lgtm

**Pull request merged**
