### PR TITLE
OCPBUGS-25766: manifests/0000_31_cluster-baremetal-operator_06_deployment: Enable leader election

### PR DESCRIPTION
**Pull request by wking**
The option has been available for years:

```console
$ git blame main.go | grep enable-leader-election
dcbe86f72 (Sandhya Dasu               2020-08-18 21:09:29 -0400  72)    flag.BoolVar(&enableLeaderElection, "enable-leader-election", false,
```

and without it overlapping operator pods [can crash-loop](https://issues.redhat.com/browse/OCPBUGS-25766):

```
  : [sig-cluster-lifecycle] pathological event should not see excessive Back-off restarting failed containers	0s
  {  event [namespace/openshift-machine-api node/ip-10-0-62-147.us-west-2.compute.internal pod/cluster-baremetal-operator-574577fbcb-z8nd4 hmsg/bf39bb17ae - Back-off restarting failed container cluster-baremetal-operator in pod cluster-baremetal-operator-574577fbcb-z8nd4_openshift-machine-api(441969c1-b430-412c-b67f-4ae2f7797f4f)] happened 26 times
  event [namespace/openshift-machine-api node/ip-10-0-62-147.us-west-2.compute.internal pod/cluster-baremetal-operator-574577fbcb-z8nd4 hmsg/bf39bb17ae - Back-off restarting failed container cluster-baremetal-operator in pod cluster-baremetal-operator-574577fbcb-z8nd4_openshift-machine-api(441969c1-b430-412c-b67f-4ae2f7797f4f)] happened 51 times}
```

while fighting each other over the same ClusterOperator status:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.16-upgrade-from-stable-4.15-e2e-aws-ovn-upgrade/1737335551998038016/artifacts/e2e-aws-ovn-upgrade/gather-audit-logs/artifacts/audit-logs.tar | tar -xz --strip-components=2
$ zgrep -h '"resource":"clusteroperators","name":"baremetal"' kube-apiserver/*audit*log.gz | jq -r 'select(.verb == "create" or .verb == "update") | .stageTimestamp + " " + .verb + " " + (.responseStatus.code | tostring) + " " + (.objectRef.subresource) + " " + .user.username + " " + .user.extra["authentication.kubernetes.io/pod-name"][0]' | grep 'T06:08:.*cluster-baremetal-operator' | sort
2023-12-20T06:08:21.757799Z update 200 status system:serviceaccount:openshift-machine-api:cluster-baremetal-operator cluster-baremetal-operator-574577fbcb-z8nd4
2023-12-20T06:08:21.778638Z update 200 status system:serviceaccount:openshift-machine-api:cluster-baremetal-operator cluster-baremetal-operator-7fbb57959b-s9v9g
2023-12-20T06:08:21.780378Z update 409 status system:serviceaccount:openshift-machine-api:cluster-baremetal-operator cluster-baremetal-operator-574577fbcb-z8nd4
2023-12-20T06:08:21.790000Z update 200 status system:serviceaccount:openshift-machine-api:cluster-baremetal-operator cluster-baremetal-operator-7fbb57959b-s9v9g
2023-12-20T06:08:21.802780Z update 200 status system:serviceaccount:openshift-machine-api:cluster-baremetal-operator cluster-baremetal-operator-7fbb57959b-s9v9g
```

Using a leader lock will avoid this contention, and the system should be able to coast through brief moments after an outgoing leader leaves until a replacement leader picks things back up.

I'm also setting [a `Recreate` strategy][2], because:

1. Incoming pod surged by the default Deployment strategy.
2. Incoming pod attempts to acquire the Lease, but the outgoing pod is holding it.
3. Outgoing pod releases the lease and exits.
4. Incoming pod tries again, and this time acquires the lease.

can be slow in the 3-to-4 phase, while:

1. Outgoing pod releases the lease and exits.
2. Incoming pod created, scheduled, and acquires the lease.

tends to be faster.  And again, the component should be able to coast through small durations without a functioning leader.

See openshift/machine-config-operator@7530ded86 (openshift/machine-config-operator#3895) for another example of how Recreate can help that way.

[2]: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment

### CODE REVIEW

**Comment by zaneb** [comment]
```
2023-12-21T03:13:11.148334181Z E1221 03:13:11.148220       1 main.go:104] "unable to start manager" err="LeaderElectionID must be configured"
````

**Comment by wking** [comment]
> ...LeaderElectionID must be configured...

Oops, thanks.  I've pushed:

```console
$ git --no-pager diff 4e4519d6..3be7317c
diff --git a/main.go b/main.go
index 4846efd1..7af5a72c 100644
--- a/main.go
+++ b/main.go
@@ -98,7 +98,9 @@ func main() {
                }),
                NewCache: cache.MultiNamespacedCacheBuilder(
                        []string{controllers.ComponentNamespace, provisioning.OpenshiftConfigNamespace}),
-               LeaderElection: enableLeaderElection,
+               LeaderElection:          enableLeaderElection,
+               LeaderElectionID:        "cluster-baremetal-operator",
+               LeaderElectionNamespace: os.Getenv("COMPONENT_NAMESPACE"),
        })
        if err != nil {
                klog.ErrorS(err, "unable to start manager")
```

And added a paragraph to the 3be7317c commit message talking myself through that change.

**Comment by wking** [comment]
More pattern-matching consistency:

```console
$ git --no-pager diff 3be7317c..0cfaf393
diff --git a/main.go b/main.go
index 7af5a72c..e6bb56d5 100644
--- a/main.go
+++ b/main.go
@@ -100,7 +100,7 @@ func main() {
                        []string{controllers.ComponentNamespace, provisioning.OpenshiftConfigNamespace}),
                LeaderElection:          enableLeaderElection,
                LeaderElectionID:        "cluster-baremetal-operator",
-               LeaderElectionNamespace: os.Getenv("COMPONENT_NAMESPACE"),
+               LeaderElectionNamespace: controllers.ComponentNamespace,
        })
        if err != nil {
                klog.ErrorS(err, "unable to start manager")
```

**Comment by wking** [comment]
Hrm, I need to extend RBAC:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-metal-ipi-ovn-ipv6/1737877679555743744/artifacts/e2e-metal-ipi-ovn-ipv6/gather-extra/artifacts/pods/openshift-machine-api_cluster-baremetal-operator-f9696655-p5dxv_cluster-baremetal-operator.log | tail -n1
E1221 19:31:10.136115       1 leaderelection.go:332] error retrieving resource lock openshift-machine-api/cluster-baremetal-operator: leases.coordination.k8s.io "cluster-baremetal-operator" is forbidden: User "system:serviceaccount:openshift-machine-api:cluster-baremetal-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "openshift-machine-api"
```

**Comment by wking** [comment]
Hrm, [this preference for sharding out over a number of Roles and RoleBindings][1] will make this a bit awkward.  I'm not sure if I should:

* Shuffle that around to stuff everything into one operator-scoped role (losing flexibility for folks building kustomize without enabling leader election?  Who would do that?), or
* Pivot the many entries from probably-not-unique-enough vs. other `openshift-machine-api` inhabitants names like `leader-election-role` to more unique-but-unweildy names like `cluster-baremetal-operator-leader-election-rolebinding`.

[1]: https://github.com/openshift/cluster-baremetal-operator/blame/18c66142a2349aa2324522f8300e8ffca894985c/config/rbac/kustomization.yaml#L9-L10

**Comment by wking** [comment]
Trying to understand what's going on with ServiceAccounts and RBAC in [the `e2e-agnostic-ovn` run][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-agnostic-ovn/1737988020168036352/artifacts/e2e-agnostic-ovn/gather-extra/artifacts/pods.json | jq -c '.items[] | select(.metadata.namespace == "openshift-machine-api") | {name: .metadata.name, serviceAccountName: .spec.serviceAccountName}'
{"name":"cluster-autoscaler-operator-6878b89c58-7kf6d","serviceAccountName":"cluster-autoscaler-operator"}
{"name":"cluster-baremetal-operator-5c57b874f5-s9zmq","serviceAccountName":"cluster-baremetal-operator"}
{"name":"control-plane-machine-set-operator-7d5dcfcb76-cshv4","serviceAccountName":"control-plane-machine-set-operator"}
{"name":"machine-api-controllers-54c98b4bb4-sgvhd","serviceAccountName":"machine-api-controllers"}
{"name":"machine-api-operator-7fb4f8c4fb-7gr2t","serviceAccountName":"machine-api-operator"}
```

So each pod has its own ServiceAccount.  Good.  Checking on bound roles:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-agnostic-ovn/1737988020168036352/artifacts/e2e-agnostic-ovn/gather-extra/artifacts/rolebindings.json | jq -c '.items[] | select(.metadata.namespace == "openshift-machine-api") | {name: .metadata.name, subjects, roleRef, description: .metadata.annotations["openshift.io/description"]}'
{"name":"cluster-autoscaler","subjects":[{"kind":"ServiceAccount","name":"cluster-autoscaler","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"cluster-autoscaler"},"description":null}
{"name":"cluster-autoscaler-operator","subjects":[{"kind":"ServiceAccount","name":"cluster-autoscaler-operator","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"cluster-autoscaler-operator"},"description":null}
{"name":"cluster-baremetal-operator","subjects":[{"kind":"ServiceAccount","name":"cluster-baremetal-operator","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"cluster-baremetal-operator"},"description":null}
{"name":"control-plane-machine-set-operator","subjects":[{"kind":"ServiceAccount","name":"control-plane-machine-set-operator","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"control-plane-machine-set-operator"},"description":null}
{"name":"machine-api-controllers","subjects":[{"kind":"ServiceAccount","name":"machine-api-controllers","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"machine-api-controllers"},"description":null}
{"name":"machine-api-operator","subjects":[{"kind":"ServiceAccount","name":"machine-api-operator","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"machine-api-operator"},"description":null}
{"name":"prometheus-k8s-cluster-autoscaler-operator","subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"openshift-monitoring"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s-cluster-autoscaler-operator"},"description":null}
{"name":"prometheus-k8s-cluster-baremetal-operator","subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"openshift-monitoring"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s-cluster-baremetal-operator"},"description":null}
{"name":"prometheus-k8s-machine-api-operator","subjects":[{"kind":"ServiceAccount","name":"prometheus-k8s","namespace":"openshift-monitoring"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"prometheus-k8s-machine-api-operator"},"description":null}
{"name":"system:deployers","subjects":[{"kind":"ServiceAccount","name":"deployer","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:deployer"},"description":"Allows deploymentconfigs in this namespace to rollout pods in this namespace.  It is auto-managed by a controller; remove subjects to disable."}
{"name":"system:image-builders","subjects":[{"kind":"ServiceAccount","name":"builder","namespace":"openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:image-builder"},"description":"Allows builds in this namespace to push images to this namespace.  It is auto-managed by a controller; remove subjects to disable."}
{"name":"system:image-pullers","subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"Group","name":"system:serviceaccounts:openshift-machine-api"}],"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"system:image-puller"},"description":"Allows all pods in this namespace to pull images from this namespace.  It is auto-managed by a controller; remove subjects to disable."}
```

`openshift.io/description` seems unnecessarily OpenShift-specific, when [upstream declares `kubernetes.io/description`][2].  I'd expect standardizing on the upstream tag would make it easier for people and robots to find the description, by allowing them to avoid wondering "will this be a Kubernetes description, or an OpenShift description?".  But that's orthogonal to RBAC.

And it seems a bit strange that `cluster-autoscaler-operator`, `cluster-baremetal-operator`, and `machine-api-operator` set up `prometheus-k8s-*` RoleBindings, while `control-plane-machine-set-operator` does not.  But perhaps CPMS recycles `prometheus-k8s-machine-api-operator` or something.

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-agnostic-ovn/1737988020168036352/artifacts/e2e-agnostic-ovn/gather-extra/artifacts/roles.json | jq -c '.items[] | select(.metadata.namespace == "openshift-machine-api") | ([.rules[] | select(.resources | tostring | contains("leases"))]) | select(length > 0)' | sort | uniq -c
      1 [{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["get","list","create","update"]}]
      3 [{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["get","list","watch","create","update","patch","delete"]}]
      1 [{"apiGroups":[""],"resources":["configmaps","leases","secrets","services"],"verbs":["create","delete","get","list","patch","update","watch"]}]
```

Aha, I'd missed `"apiGroups":["coordination.k8s.io"]`.  Hopefully fixed with 8f95164d -> f8e3ac9c.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-agnostic-ovn/1737988020168036352
[2]: https://kubernetes.io/docs/reference/labels-annotations-taints/#description

**Comment by wking** [comment]
[This ingress flake][1] is unrelated.  Otherwise CI is looking pretty good now, so probably ready for a fresh review round when folks have time.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-baremetal-operator/395/pull-ci-openshift-cluster-baremetal-operator-master-e2e-metal-ipi-sdn-upgrade/1738197607332712448

**Pull request merged**
