### PR TITLE
Revert "Use private ports for Ironic from BMO when proxy is on"

### PR DESCRIPTION
**Pull request by dtantsur**
Reverts openshift/cluster-baremetal-operator#353

### CODE REVIEW

**Comment by dtantsur** [comment]
/hold

To be merged if https://github.com/openshift/cluster-baremetal-operator/pull/354 does not help.

**Comment by honza** [comment]
Let's indicate the reason for reverting in the commit message.

**Comment by dtantsur** [comment]
/close

The alternative patch has passed CI and has been merged. Let's hope the revert is not needed.

**Pull request closed without merging**
