### PR TITLE
[release-4.7] Bug 1973367: Pass IP_OPTIONS=dhcp|dhcp6 down to OS Downloader container

### PR DESCRIPTION
**Pull request by asalkeld**
This is a squashed backport of the following commits
- https://github.com/openshift/cluster-baremetal-operator/commit/da0fdb5627d71ed60bcc1a5dfac8e9360b0d33a1
- https://github.com/openshift/cluster-baremetal-operator/commit/126f94f94e0d2720a49e149f57a6e2ec31e0bf33
- https://github.com/openshift/cluster-baremetal-operator/commit/5d37ad30322b511361c352ade461c96f5540190b
- https://github.com/openshift/cluster-baremetal-operator/commit/4589e4c490154ea20d6b28c69283ce3a6efd278f
- https://github.com/openshift/cluster-baremetal-operator/commit/9073a729a3a90d94d84be3f5baa8e0449c29aa41
- https://github.com/openshift/cluster-baremetal-operator/commit/392448754b540c995f13b05884d22ab0fc75428c

### CODE REVIEW

**Comment by honza** [comment]
-1 on squashing as it impedes git archeology; cherry-picking with -x is preferred

**Comment by asalkeld** [comment]
> -1 on squashing as it impedes git archeology; cherry-picking with -x is preferred

The commits needed significant changes. So I ended up just diffing the master with release-4.7 - which was easier.
Basically I didn't even cherry-pick in the end.

**Comment by honza** [comment]
> The commits needed significant changes. So I ended up just diffing the master with release-4.7 - which was easier.
Basically I didn't even cherry-pick in the end.

/lgtm

**Comment by dhellmann** [comment]
Removing cherry-pick-approved because the test jobs are failing and the merge window is closed for this week.

**Comment by dhellmann** [comment]
Removed cherry-pick-approved until the tests are working.

**Comment by asalkeld** [comment]
This keeps failing
```
: [sig-instrumentation] Prometheus when installed on the cluster shouldn't report any alerts in firing state apart from Watchdog and AlertmanagerReceiversNotConfigured 
```
not related to what this PR is doing afaik

**Pull request merged**
