### PR TITLE
OCPBUGS-20808: Uplift x/net to v0.17.0

### PR DESCRIPTION
**Pull request by elfosardo**

### CODE REVIEW

**Comment by derekhiggins** [comment]
@elfosardo linting jobs failed, looks like the same problem I had, I needed to bump  golangci/golangci-lint to v1.42.1 (don't go to latest you'll have other problems with changes in the formatting required by the linter)

see ICC in 4.10 https://github.com/openshift/image-customization-controller/pull/108

**Comment by elfosardo** [comment]
> @elfosardo linting jobs failed, looks like the same problem I had, I needed to bump golangci/golangci-lint to v1.42.1 (don't go to latest you'll have other problems with changes in the formatting required by the linter)
> 
> see ICC in 4.10 [openshift/image-customization-controller#108](https://github.com/openshift/image-customization-controller/pull/108)

thanks @derekhiggins ! I'll have a look

**Pull request closed without merging**
