### PR TITLE
Update BMH CRD from metal3-io/baremetal-operator

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by hardys** [comment]
@honza lgtm - but note you may want to rebase the BMO PR again, as this also picked up https://github.com/metal3-io/baremetal-operator/commit/6ddbbd25be84ed9eff1a534c9906fdf16a2551bd

**Comment by dtantsur** [comment]
Would it be possible to also include the changes from https://github.com/metal3-io/baremetal-operator/pull/786 or should I propose them separately?

**Comment by honza** [comment]
> Would it be possible to also include the changes from metal3-io/baremetal-operator#786 or should I propose them separately?

Done

**Review by dtantsur — APPROVED** [review]

**Pull request merged**
