### PR TITLE
OCPBUGS-31341: Refactor Pull Secret application

### PR DESCRIPTION
**Pull request by zaneb**

### CODE REVIEW

**Comment by elfosardo** [comment]
this looks ok to me
I don't think the failures we're seeing depend on the change, but I will give the metal jobs one more chance

**Comment by zaneb** [comment]
Confirmed from the CI logs that the Secret is not churning (CreationTimestamp and update time are the same).

Not sure what is happening with the other CI jobs, but it appears unrelated.
/retest-required

**Pull request merged**
