### PR TITLE
Bug 2099928: Add UT for image_customization_test

### PR DESCRIPTION
**Pull request by zhouhao3**
Follow-up to #240

### CODE REVIEW

**Comment by zhouhao3** [comment]
Follow-up to #240

**Comment by zhouhao3** [comment]
@elfosardo @dtantsur It looks like this PR requires the bugzilla/valid-bug label to merge, but there is no corresponding bugzilla. Is there a way to merge directly?

**Comment by fenggw-fnst** [comment]
This PR is for the main branch, rather than for a specific branch or bug, so can we skip the bugzilla/valid-bug label? Could you please take a look? @elfosardo @dtantsur Thanks a lot!

**Comment by elfosardo** [comment]
@fenggw-fnst hi! Since we're in Feature Freeze period, this will indeed need a BZ, thanks!

**Pull request merged**
