### PR TITLE
Remove asalkeld and kirankt from Owners

### PR DESCRIPTION
**Pull request by kirankt**
Remove asalkeld and kirankt from Owners

### CODE REVIEW

**Comment by sadasu** [comment]
@kirankt we need a BZ for this.

**Comment by kirankt** [comment]
> @kirankt we need a BZ for this.

Ugh. This is not urgent. We can hold off until 4.11 branch opens. Thanks.

**Comment by zaneb** [comment]
I think there's a way to override the BZ requirement, but possibly only @hardys can do that.

**Pull request merged**
