### PR TITLE
add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by guillaumerose**
This is matches openshift/enhancements#414 and doesn't change existing behavior

### CODE REVIEW

**Comment by andfasano** [comment]
Hi @guillaumerose I have a question: the enhancement proposes that manifests must contain at least one inclusion annotation, and the default profile is `self-managed-highly-available`. I was looking for a more formal definition in the enh proposal for `self-managed-highly-available` but didn't found anything (except for [this](https://github.com/openshift/enhancements/blob/6eb55f8a78318b977420c4bddc1e5a2474ad50ac/enhancements/update/cluster-profiles.md#design)). Do you have any link with additional info and/or can clarify? Thanks

**Comment by guillaumerose** [comment]
Hi @andfaso. The naming discussion started in this comment https://github.com/openshift/enhancements/pull/414#issuecomment-675491233. I don't have much than this thread. The main point is that they prefer explicit over implicit inclusion and `default` as a name was not really a good name.
This change is also tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1871890

**Comment by andfasano** [comment]
> Hi @andfaso. The naming discussion started in this comment [openshift/enhancements#414 (comment)](https://github.com/openshift/enhancements/pull/414#issuecomment-675491233). I don't have much than this thread. The main point is that they prefer explicit over implicit inclusion and `default` as a name was not really a good name.
> This change is also tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1871890

Thanks. Some of the existing resources already had an exclusion profile define (`exclude.release.openshift.io/internal-openshift-hosted: "true"`), do you maybe have any idea if it's ok to have both the exclusion _and_ inclusion annotations set (I think so)?

**Comment by dhellmann** [comment]
> > Hi @andfaso. The naming discussion started in this comment [openshift/enhancements#414 (comment)](https://github.com/openshift/enhancements/pull/414#issuecomment-675491233). I don't have much than this thread. The main point is that they prefer explicit over implicit inclusion and `default` as a name was not really a good name.
> > This change is also tracked here: https://bugzilla.redhat.com/show_bug.cgi?id=1871890
> 
> Thanks. Some of the existing resources already had an exclusion profile define (`exclude.release.openshift.io/internal-openshift-hosted: "true"`), do you maybe have any idea if it's ok to have both the exclusion _and_ inclusion annotations set (I think so)?

Yes, it should be fine. Only the annotation for the profile being used is examined. See https://github.com/openshift/enhancements/blob/master/enhancements/update/cluster-profiles.md for details.

/approve

**Pull request merged**
